# Generated by Django 6.0 on 2026-03-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_nest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
